# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='values',
        ),
        migrations.AddField(
            model_name='datalist',
            name='foo',
            field=models.CharField(default='1024', max_length=100),
        ),
    ]
